### ISSUE TITLE
Deprecated selector in `ruby-block/styles/ruby-block.less`

### ISSUE THREAD

**Issue by zarembas** [hmatsuda/ruby-block#26]
In `ruby-block/styles/ruby-block.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host .line-number.ruby-block-highlight,
atom-text-editor .line-number.ruby-block-highlight,
atom-text-editor::shadow .line-number.ruby-block-highlight` => `:host .line-number.ruby-block-highlight,
atom-text-editor .line-number.ruby-block-highlight,
atom-text-editor.editor .line-number.ruby-block-highlight`

* `:host .highlights .ruby-block-highlight .region,
atom-text-editor .highlights .ruby-block-highlight .region,
atom-text-editor::shadow .highlights .ruby-block-highlight .region` => `:host .highlights .ruby-block-highlight .region,
atom-text-editor .highlights .ruby-block-highlight .region,
atom-text-editor.editor .highlights .ruby-block-highlight .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by mirineumark** [comment]
+1

**Comment by scepion1d** [comment]
+1

**Comment by liam-ngy** [comment]
+1

**Comment by jokius** [comment]
+1

**Comment by q-ra** [comment]
+1
