### ISSUE TITLE
ruby-block stop working after atom upgrade to 1.3.0

### ISSUE THREAD

**Issue by fidalgo** [hmatsuda/ruby-block#33]
Since the https://github.com/atom/language-ruby was updated to use the tree-sitter https://github.com/atom/language-ruby/pull/225 it stopped working.

**Comment by hmatsuda** [comment]
@fidalgo I also use atom-1.30.0 but I don't reproduce this problem.
Can you give me details for to reproduce this bug?

**Comment by fidalgo** [comment]
@hmatsuda sorry for opening this, but after starting atom with a clean state (moved `~./atom` to `~./atom-backup` and started again, it's working again. Now I will try to find the culprit.
