### ISSUE TITLE
Support for else and when?

### ISSUE THREAD

**Issue by envygeeks** [hmatsuda/ruby-block#8]
I would be super happy if you would support else and when as well!

**Comment by hmatsuda** [comment]
@envygeeks I'll publish new version with this feature.
![ruby-block](https://cloud.githubusercontent.com/assets/1421898/6545326/30d7c264-c5c5-11e4-8427-e98c984b83ff.gif)

**Comment by envygeeks** [comment]
:+1: that's legit, I love it.
